### ISSUE TITLE
HTTPError: 400

### ISSUE THREAD

**Issue by adot08** [markuswt/gpt-commit#4]
Hi, I tried to evoke gpt-commit.py and got the following error:
Traceback (most recent call last):
  File "./gpt-commit/gpt-commit.py", line 85, in <module>
    summaries = summarize_added_modified() + "\n\n" + summarize_deleted(
  File "./gpt-commit/gpt-commit.py", line 59, in summarize_added_modified
    [summarize_diff(get_diff(file)) for file in modified_files])
  File "./gpt-commit/gpt-commit.py", line 59, in <listcomp>
    [summarize_diff(get_diff(file)) for file in modified_files])
  File "./gpt-commit/gpt-commit.py", line 35, in summarize_diff
    return complete(DIFF_PROMPT + "\n\n" + diff + "\n\n")
  File "./gpt-commit/gpt-commit.py", line 28, in complete
    response.raise_for_status()
  File "/mnt/users/adot/CondaEnvs/py_drit/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.openai.com/v1/completions

I have added OPENAI_API_KEY. Do I need any more settings about OpenAI?

**Comment by markuswt** [comment]
Setting `OPENAI_API_KEY` should suffice. Could you print and look at the headers and body in `complete`?

**Comment by joerndyherrn** [comment]
fixed with https://github.com/markuswt/gpt-commit/pull/5

**Comment by markuswt** [comment]
> I got the same when my commit contained binaries.

Fixed this now
